steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-production-app-dev:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-production-app-dev:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'doc-production-app-dev'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-production-app-dev:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=us-central1,STORAGE_BUCKET=$PROJECT_ID-doc-assets,APP_ENV=dev,APP_VERSION=1.1.0-$SHORT_SHA'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '3600'
      - '--execution-environment'
      - 'gen2'
      - '--cpu'
      - '2'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-production-app-dev:latest'

options:
  logging: CLOUD_LOGGING_ONLY
