steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-augmented:latest'
      - '.'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-augmented:latest'

  # Step 3: Deploy to Cloud Run as separate service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy doc-app-research-augmented \
          --image "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run/doc-app-research-augmented:latest" \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=us-central1,STORAGE_BUCKET=$PROJECT_ID-doc-assets-researchaug,APP_ENV=researchaug,APP_VERSION=research-aug-$SHORT_SHA" \
          --memory 2Gi \
          --timeout 3600 \
          --cpu 2

options:
  logging: CLOUD_LOGGING_ONLY
